name: Java CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: validate gradle wrapper
      uses: gradle/wrapper-validation-action@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: gradle
    - name: Grant permissions
      run: chmod +x gradlew
    - name: Build Skript
      run: ./gradlew clean build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: Skript
        path: build/libs/*
